select distinct ci.ClinicID, 
ci.ARTnumber as ARTnum, 
v.vis_d as DatVisit,
'-1' as TypeVisit, 
'-1' as Womenstatus,
'-1' as PregStatus,
'1900-01-01' as DaPreg,
'-1' as ANCservice,
CAST(ROUND(ISNULL((SELECT TOP 1 CLM_v FROM tblCLM c WHERE c.ID=v.ID AND c.CLM_d=v.vis_d AND c.CLM='Weight'), 0), 0) AS INT) as Weight, 
ISNULL(b.height, 0) as Height,
'0' as Temp, 
'0' as Pulse, 
'0' as Resp, 
'/' as Blood, 
'-1' as STIPreven,
'-1' as ARTAdher,
'-1' as Birthspac,
'-1' as TBinfect,
'-1' as Partner,
'-1' as Condoms,
'-1' as CMTypeClient,
'1900-01-01' as CMDaUse,
'-1' as CMCondom,
'-1' as CoC,
'-1' as Poc,
'-1' as CMVaccine,
'-1' as UseOther,
'-1' as OCMcondom,
'-1' as OCoc,
'-1' as OPoC,
'-1' as OCMVaccin,
'-1' as OCMother,
0 as Cough, 
0 as Fever,
0 as Wlost, 
0 as Drenching,
0 as Urine,
0 as Genital,
0 as Chemnah,
'-1' as Hospital, 
'0' as NumDay, 
'' as CauseHospital, 
'-1' as MissARV, 
'0' as MissTime, 
ISNULL(b.WHOinclusion, '-1') as WHO, 
'-1' as Eligible, 
'' as TestID, 
'-1' as [Function], 
-1 as TB, 
'-1' as TypeTB, 
-1 as TBtreat,
'1900-01-01' as DaTBtreat, 
'' as TestHIV, 
'-1' as ResultHIV,
'-1' as ReCD4, 
'-1' as ReVL, 
'-1' as ReHCV,
'-1' as CrAG, 
'-1' as CrAGResult, 
'-1' as VLDetectable, 
'-1' as Referred, 
'-1' as OReferred,
'-1' as Moderate,
'-1' as Renal,
'-1' as Rash,
'-1' as Hepatitis,
'-1' as Peripheral,
'-1' as Neutropenia,
'-1' as Hyperlipidemia,
'-1' as Lactic,
'-1' as Hypersensitivity,
'-1' as Jaundice,
'-1' as MTother,
'-1' as ARVreg,
'-1' as ResultHC,
null as TPTout,
null as TBout,
ISNULL(v.NextAppoin_d, '1900-01-01') as DaApp,
ci.ClinicID + right('0'+cast(day(v.vis_d) as varchar(2)),2) + right('0'+cast(Month(v.vis_d) as varchar(2)),2) + right(cast(year(v.vis_d) as varchar(4)),2) as Vid
from tblVIS v
left join tblCodeID ci on ci.PtCode=v.ID 
left outer join tblBAS b on b.ID=v.ID
where ci.ClinicId is not null;
